### PR TITLE
Fix downloading bugs

### PR DESCRIPTION
**Pull request by karwler**
While testing the program on Manjaro, I encountered a few bugs which this commit should fix:
1. While downloading from multiple pages from a library URL without an '&', the program would just iterate over the same page multiple times and append a second 'page' query to the URL, rather than modifying the existing one.
2. The view mode wouldn't get properly set on certain pages, causing only 10 stories at most to be downloaded.
3. On some pages, the links use a 'story_name' class rather than 'story_link', causing nothing to be downloaded. I don't know why it's sometimes like this, but I could reliably replicate this behavior by downloading the page with wget or curl.
4. Some filenames with special characters didn't get decoded properly.

### CODE REVIEW

**Comment by karwler** [comment]
I have a question regarding the ```translator = {...}``` line in ```save_files```. At first I assumed it's a list of characters which aren't allowed in Windows filenames. However if that'd be the case then I don't know why ```ã``` is in there? But if this is indeed supposed to be a list of prohibited filename characters, I'd also like to add a specific list for UNIX-based systems to this commit. It's just that at this moment I'm not sure whether my assumption is correct.

**Comment by GameBiit** [comment]
> I have a question regarding the `translator = {...}` line in `save_files`. At first I assumed it's a list of characters which aren't allowed in Windows filenames. However if that'd be the case then I don't know why `ã` is in there? But if this is indeed supposed to be a list of prohibited filename characters, I'd also like to add a specific list for UNIX-based systems to this commit. It's just that at this moment I'm not sure whether my assumption is correct.

Yes, this is exactly for that purpose. That strange letter was a strange square bracket or something similar in the source name. Whatever the case, this letter does not fit a filename because it was not in the source name.

**Comment by karwler** [comment]
> > I have a question regarding the `translator = {...}` line in `save_files`. At first I assumed it's a list of characters which aren't allowed in Windows filenames. However if that'd be the case then I don't know why `ã` is in there? But if this is indeed supposed to be a list of prohibited filename characters, I'd also like to add a specific list for UNIX-based systems to this commit. It's just that at this moment I'm not sure whether my assumption is correct.
> 
> Yes, this is exactly for that purpose. That strange letter was a strange square bracket or something similar in the source name. Whatever the case, this letter does not fit a filename because it was not in the source name.

Alright, I've left the common ```/``` and characters that aren't listed [here](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) to still apply across all platforms and isolated the rest for Windows only.

**Comment by GameBiit** [comment]
> While testing the program on Manjaro, I encountered a few bugs which this commit should fix:
> 
> 1. While downloading from multiple pages from a library URL without an '&', the program would just iterate over the same page multiple times and append a second 'page' query to the URL, rather than modifying the existing one.
> 2. The view mode wouldn't get properly set on certain pages, causing only 10 stories at most to be downloaded.
> 3. On some pages, the links use a 'story_name' class rather than 'story_link', causing nothing to be downloaded. I don't know why it's sometimes like this, but I could reliably replicate this behavior by downloading the page with wget or curl.
> 4. Some filenames with special characters didn't get decoded properly.

The problem with showing 'story_name'  instead of 'story_link' is related to maintaining the session. When you don't maintain it, it shows 'story_name' in bookshelfs, search results, popular stories, latest stories etc. Folders and the main page are unaffected.

**Comment by GameBiit** [comment]
Sometimes names of files are the same. It only saves one file then because the previous one is overwritten.

**Comment by karwler** [comment]
> Sometimes names of files are the same. It only saves one file then because the previous one is overwritten.

You mean for when different stories have the same title? Should I add a fix for it in this commit or is that for another time?

**Comment by karwler** [comment]
> Sometimes names of files are the same. It only saves one file then because the previous one is overwritten.

I’ve added a simple function that appends a story’s id to the filename if a file with the same name already exists, presumably because of different stories with the same title. Also I’ve moved everything filename related into a separate commit, to keep it less convoluted. There’s now an additional fallback for the possibility of a failure to parse the content-dispositions. While doing some more digging, I noticed that the odd translator characters appear to be a result of the former decoding issues which should be fixed now and so I’ve taken them out, since they’re not strictly forbidden by any documentation I could find. Additionally I’ve cleaned up lines that were causing warnings in PyCharm.

**Pull request merged**
